CREATE DATABASE ArtGallery_DB;

Use ArtGallery_DB;

CREATE TABLE CITY (
    CityID INT PRIMARY KEY AUTO_INCREMENT,
    CityName VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL
);

CREATE TABLE EXHIBITION_INFO (
    ExhibID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Theme VARCHAR(255)
);

CREATE TABLE ARTIST (
    ArtistID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    BirthYear INT,
    CityID INT,
    FOREIGN KEY (CityID) REFERENCES CITY(CityID) ON DELETE SET NULL
);

CREATE TABLE MEMBER (
    MemberID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    CityID INT,
    FOREIGN KEY (CityID) REFERENCES CITY(CityID) ON DELETE SET NULL
);

CREATE TABLE GALLERY (
    GalleryID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Rating DECIMAL(3, 1),
    CityID INT,
    FOREIGN KEY (CityID) REFERENCES CITY(CityID) ON DELETE SET NULL
);

CREATE TABLE ARTWORK (
    ArtworkID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    ArtistID INT NOT NULL,
    Type VARCHAR(100),
    Price DECIMAL(10, 2),
    Status VARCHAR(50) DEFAULT 'Available',
    FOREIGN KEY (ArtistID) REFERENCES ARTIST(ArtistID) ON DELETE CASCADE
);

CREATE TABLE WORKSHOP_INFO (
    WS_ID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    InstructorID INT NOT NULL,
    Price DECIMAL(10, 2),
    Level VARCHAR(50),
    FOREIGN KEY (InstructorID) REFERENCES ARTIST(ArtistID) ON DELETE CASCADE
);

CREATE TABLE EXHIBITION_SCHEDULE (
    ExhibID INT NOT NULL,
    GalleryID INT NOT NULL,
    StartDate DATE NOT NULL,
    PRIMARY KEY (ExhibID, GalleryID),
    FOREIGN KEY (ExhibID) REFERENCES EXHIBITION_INFO(ExhibID) ON DELETE CASCADE,
    FOREIGN KEY (GalleryID) REFERENCES GALLERY(GalleryID) ON DELETE CASCADE
);

CREATE TABLE WORKSHOP_SCHEDULE (
    WS_ID INT NOT NULL,
    Date DATE NOT NULL,
    PRIMARY KEY (WS_ID, Date),
    FOREIGN KEY (WS_ID) REFERENCES WORKSHOP_INFO(WS_ID) ON DELETE CASCADE
);

CREATE TABLE PARTICIPATION (
    MemberID INT NOT NULL,
    WS_ID INT NOT NULL,
    PRIMARY KEY (MemberID, WS_ID),
    FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID) ON DELETE CASCADE,
    FOREIGN KEY (WS_ID) REFERENCES WORKSHOP_INFO(WS_ID) ON DELETE CASCADE
);
